### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by demogitcourse** [rkassanjee/training2021#2]
This is an example of an issue to let you know about a PR #1 that I submitted for a missing file. You don't have to do anything right now and will be able to resolve it during part 2 of the course.

**Comment by rkassanjee** [comment]
Thanks for noticing this. let me work on it.

**Comment by rkassanjee** [comment]
I have now resolved this with f211f618135e69859de9180eb74f6af61136b508

**Comment by rkassanjee** [comment]
So I should have closed this, with f211f618135e69859de9180eb74f6af61136b508.
